[project]
org-name = "ballerina"
version = "1.1.1"

[dependencies]
"ballerina/runtime" = "0.5.1"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "task"
    version = "1.1.1-SNAPSHOT"
    path = "../task-native/build/libs/task-native-1.1.1-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["task"]

    [[platform.libraries]]
    artifactId = "quartz"
    version = "2.3.1"
    path = "./lib/quartz-2.3.1.jar"
    groupId = "org.quartz-scheduler"
    modules = ["task"]
